services:
  - type: web
    name: schubase
    runtime: docker
    plan: free
    repo: https://github.com/Chemscreen/First-Pro
    branch: main
    healthCheckPath: /login
    envVars:
      - key: DREXEL_USERNAME
        sync: false
      - key: DREXEL_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SCHUBASE_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
